# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Graduation Project/Narrowband-IoT-Receiver/src/coarse_synchronizer/coarse_synchronizer.srcs/sources_1/bd/dual_port_ram/ip/dual_port_ram_blk_mem_gen_0_1/dual_port_ram_blk_mem_gen_0_1.xci
# IP: The module: 'dual_port_ram_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Graduation Project/Narrowband-IoT-Receiver/src/coarse_synchronizer/coarse_synchronizer.srcs/sources_1/bd/dual_port_ram/ip/dual_port_ram_blk_mem_gen_0_1/dual_port_ram_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_ram_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Graduation Project/Narrowband-IoT-Receiver/src/coarse_synchronizer/coarse_synchronizer.srcs/sources_1/bd/dual_port_ram/ip/dual_port_ram_blk_mem_gen_0_1/dual_port_ram_blk_mem_gen_0_1.xci
# IP: The module: 'dual_port_ram_blk_mem_gen_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Graduation Project/Narrowband-IoT-Receiver/src/coarse_synchronizer/coarse_synchronizer.srcs/sources_1/bd/dual_port_ram/ip/dual_port_ram_blk_mem_gen_0_1/dual_port_ram_blk_mem_gen_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dual_port_ram_blk_mem_gen_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
