# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Working/Digital Design/Graduation Project/Repo/Narrowband-IoT-Receiver/src/viterbi_decoder/viterbi_decoder.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
# IP: The module: 'bram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Working/Digital Design/Graduation Project/Repo/Narrowband-IoT-Receiver/src/viterbi_decoder/viterbi_decoder.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Working/Digital Design/Graduation Project/Repo/Narrowband-IoT-Receiver/src/viterbi_decoder/viterbi_decoder.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0.xci
# IP: The module: 'bram_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Working/Digital Design/Graduation Project/Repo/Narrowband-IoT-Receiver/src/viterbi_decoder/viterbi_decoder.srcs/sources_1/bd/bram/ip/bram_blk_mem_gen_0_0/bram_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
