set_property SRC_FILE_INFO {cfile:F:/Etisalat/GP/RTL/Fine_Sync/Fine_Sync.srcs/constrs_1/new/cons.xdc rfile:../../../Fine_Sync.srcs/constrs_1/new/cons.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
create_pblock pblock_1
add_cells_to_pblock [get_pblocks pblock_1] -top
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM8 [get_ports {o_NRS_generated_address2[0]}]
set_property src_info {type:XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM10 [get_ports {o_NRS_generated_address2[2]}]
set_property src_info {type:XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM11 [get_ports {o_NRS_generated_address2[1]}]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM9 [get_ports {o_NRS_Location[2]}]
set_property src_info {type:XDC file:1 line:473 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AK13 [get_ports {o_NRS_Location[0]}]
set_property src_info {type:XDC file:1 line:474 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL13 [get_ports {o_NRS_Location[1]}]
set_property src_info {type:XDC file:1 line:475 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL11 [get_ports {o_NRS_generated_address1[1]}]
set_property src_info {type:XDC file:1 line:476 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L10 [get_ports {o_NRS_generated_address1[2]}]
set_property src_info {type:XDC file:1 line:477 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AL10 [get_ports {o_NRS_generated_address1[0]}]
