# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/const.xdc

# Block Designs: bd/dual_port_ram/dual_port_ram.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dual_port_ram || ORIG_REF_NAME==dual_port_ram} -quiet] -quiet

# IP: bd/dual_port_ram/ip/dual_port_ram_blk_mem_gen_0_0/dual_port_ram_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dual_port_ram_blk_mem_gen_0_0 || ORIG_REF_NAME==dual_port_ram_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/dual_port_ram/dual_port_ram_ooc.xdc
